import "./globals.css";
//Layouts
import MainLayout from "./layout/layout";
import { AuthProvider } from "@/context/AuthContext";
//provider
import { ToastProvider, useToast } from "@/provider/ToastProvider";
import InitToastGlobal from "@/provider/InitToastGlobal";
//context
import { ThemeProvider } from "@/context/ThemeContext";
export const metadata = {
  title: "Tourino",
  description: "Generated by Couper.studio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased">
        <AuthProvider>
          <ToastProvider>
            <InitToastGlobal />
            <ThemeProvider>
              <MainLayout>{children}</MainLayout>
            </ThemeProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
