import "./globals.css";
//Layouts
import MainLayout from "./layout/layout";
import { AuthProvider } from "@/context/AuthContext";
export const metadata = {
  title: "Tourino",
  description: "Generated by Couper.studio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased">
        <AuthProvider>
          <MainLayout>{children}</MainLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
